//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employees.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class Table
    {
        public int Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public Nullable<System.DateTime> Start_Work_Date { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Pvd_fund_rate { get; set; }
    }

}
